### ISSUE TITLE
Prepare dataset

### ISSUE THREAD

**Issue by malteos** [airKlizz/MultiDocMultiLingualSum#1]
- Drink some coffee ;)
- Extract plain-text from Wiki dumps: https://radimrehurek.com/gensim/scripts/segment_wiki.html
- Extract source links (look for "Source" section title and external URLs)
- Save source URLs to the web archive: https://web.archive.org/ (there should be an API for the "Save Page Now" feature)
- Scrape source content directly from source or web archive (not sure what's the best way)
- Save HTML of the source (as backup)
- Extract plain text content from with one of those news scraping frameworks
- Do some sanity checks

**Comment by malteos** [comment]
I'm not really familiar with other multi-doc summarization dataset but it would be probably a good idea to have the final dataset in the same format as the existing datasets.

**Comment by airKlizz** [comment]
- I had began to extract info from XML file with regex but the gensim tool looks nice I will look at it. 
- Links are easy to extract because there are all in the same [format](https://en.wikinews.org/wiki/Wikinews:Writing_an_article#List_your_sources)
- Will also look for next steps once these 2 are done

**Comment by airKlizz** [comment]
For MultiNews the dataset is text files (one for src and one for trg). Each line correspond to one entry, so all source paragraphs on the same line for src and the summary for trg.

For WikiSum I don't know yet.

**Comment by malteos** [comment]
> For MultiNews the dataset is text files (one for src and one for trg). Each line correspond to one entry, so all source paragraphs on the same line for src and the summary for trg.
> 
> For WikiSum I don't know yet.

Removing the paragraph structure is maybe not a good idea at least for future analysis of the results. It will be probably interesting to see which paragraphs end up in the summary and which not.

**Comment by airKlizz** [comment]
The gensim tool doesn't work well with wikinews 😞. It removes links and part of the text with are inside brackets. I think templates are not exactly the same.

**Comment by airKlizz** [comment]
I made a push with scripts to extract text and sources (mainly based on the code you gave me) for german wikinews. I will try with french and english to see if it also works and then look at the web archive.

**Comment by malteos** [comment]
I found this overview of existing datasets: https://www.semanticscholar.org/paper/A-Repository-of-Corpora-for-Summarization-Dernoncourt-Ghassemi/db5abdaa1653ac8e188c963210b85364fc4c9bd7

Probably a good resource for a future paper
