### ISSUE TITLE
Index sources

### ISSUE THREAD

**Issue by airKlizz** [airKlizz/MultiDocMultiLingualSum#2]
Hi,

I am trying to index sources as we discussed (``python dataset/index_sources.py``).

The script do for each source (i.e. url) :
- one request to web.archive.org to both get archive url (if exists) and get html of achive page (if exists) (``get_archive`` in ``dataset/utils.py`` function)
- if archive not exist: one request to save page (``savepagenow.capture(url)``) and one request to get the html of the archive page
- extract info from html using ``article = NewsPlease.from_html(html, url=None)``

After the html file is saved on the html folder, same for the json file and the source is indexed in the index file.

It looks to work pretty well even if there is no text for many sources (I would say 1/3). But I checked at hand and there is many urls which are died. 

The issue is that it takes **lots of time**. When I run the script on my computer ``tqdm`` estimate between 150 and 200 hours and I tried on the server ``serv-9212`` and it is quiet the same (between 100 and 150 hours).

So I don't know if web.archive.org is slow or if try to get html pages which don't exist take lots of time but I hope we can reduce this time of computation. 

I will try to see if there are some responses on google but I was wondering that maybe you have already experiment this kind of issue. 

*Remarks:
I am not very familiar with scraping the web so maybe I didn't use the best librairies/tools available
There are few examples of html and json files that the script extracted on the server ``serv-9212`` in my directory if you want to see if it is working well before running it for many hours*

**Comment by malteos** [comment]
The HTTP requests are probably the limiting factor. 

You could multi-threading to scrape in parallel (See https://medium.com/datadriveninvestor/speed-up-web-scraping-using-multiprocessing-in-python-af434ff310c5). However this might get you blocked if you do too many requests on a single source like Web archive (multiple sources/websites will with more threads).

I also suggest keeping a log of the progress such that when you restart the script you don't need to start all over again. 

How many URLs do you want to scrape?

**Comment by airKlizz** [comment]
Yes multi-threading looks good, I will look at it (and see if we are blocked).
I agree for the log I will look at it too.
And for german wikinews there are around 35000 sources. So in the best case (if all sources are archived) we need 35000 requests and in the worste case 70000.

**Comment by airKlizz** [comment]
I change the script with multi-threading and it should take 10hours now. So I will run it tonight and see if it worked or if at one time we are blocked.

**Comment by malteos** [comment]
Maybe don't scrape all at once but do some test runs on a subset. 

When you retrieve the archive information you could also select a date right after the publication of the Wikinews article. By doing so, you would ensure that the content didn't change over time.
